name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master # або main, залежно від твоєї гілки
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Build App
        run: |
          npm install
          npm run build

      - name: Upload artifact and deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # автоматично додається GitHub
          action: "upload"
          app_location: "/" # корінь репозиторію
          output_location: "build" # або dist, якщо це Vue або інше
